import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    maxWidth: 900,
    alignSelf: 'center',
    width: '100%',
  },
  chapterNameContainer: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 1,
  },
  chapterName: {
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 5,
  },
  progressContainer: {
    position: 'absolute',
    top: 75,
    left: 0,
    right: 0,
    width: '100%',
    alignItems: 'center',
    zIndex: 1,
  },
  readerArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  readerAreaSpeed: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  readerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 600,
    paddingHorizontal: 20,
    overflow: 'hidden',
  },
  readerContentSpeed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 1000,
    paddingHorizontal: 20,
    overflow: 'hidden',
  },
  contextWordsLeft: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 0,
    maxWidth: 200,
    overflow: 'hidden',
  },
  contextWordsRight: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 0,
    maxWidth: 200,
    overflow: 'hidden',
  },
  contextWordsContainer: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
  },
  contextWord: {
    fontWeight: '300',
  },
  currentWordContainer: {
    flex: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 0,
    minWidth: 200,
  },
  word: {
    fontWeight: 'bold',
    textAlign: 'center',
  },
  wordPairContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordPairSmall: {
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: -5, // Slight overlap to bring closer to primary line
  },
  accentLetter: {
    // Color set dynamically
  },
  speedControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 10,
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
  },
  speedButton: {
    backgroundColor: '#333',
    padding: 10,
    borderRadius: 8,
    minWidth: 40,
    alignItems: 'center',
  },
  speedButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  sliderContainer: {
    flex: 1,
    alignItems: 'center',
  },
  slider: {
    width: '100%',
    height: 40,
  },
  speedInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 5,
  },
  speedText: {
    color: '#fff',
    fontSize: 14,
  },
  timeEstimate: {
    color: '#999',
    fontSize: 12,
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
    gap: 4,
    flexWrap: 'nowrap',
    maxWidth: 900,
    alignSelf: 'center',
    paddingHorizontal: 5,
  },
  button: {
    backgroundColor: '#333',
    padding: 10,
    borderRadius: 8,
    minWidth: 40,
    alignItems: 'center',
    flexShrink: 1,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
  },
  tooltip: {
    position: 'absolute',
    bottom: 150, // Higher up to avoid covering buttons
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: 8,
    borderRadius: 4,
    zIndex: 1000,
    pointerEvents: 'none', // Prevent tooltip from interfering with mouse events
  },
  tooltipText: {
    color: '#fff',
    fontSize: 12,
  },
  progressSlider: {
    width: '100%',
    maxWidth: 600,
    height: 40,
    marginBottom: 10,
  },
  progressText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 14,
    marginTop: 5,
    marginBottom: 25,
    width: '100%',
    maxWidth: 600,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 500,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
    textAlign: 'center',
  },
  scrollView: {
    maxHeight: 400,
  },
  settingSection: {
    marginBottom: 30,
  },
  settingLabel: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 10,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  colorOption: {
    width: 33,
    height: 33,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorOptionSelected: {
    borderColor: '#fff',
  },
  colorCheck: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  fontOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#333',
    borderRadius: 8,
    marginBottom: 8,
  },
  fontOptionSelected: {
    backgroundColor: '#444',
  },
  fontOptionText: {
    color: '#fff',
    fontSize: 16,
  },
  fontCheck: {
    color: '#00ff88',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalButton: {
    padding: 15,
    borderRadius: 8,
    marginTop: 20,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  chapterList: {
    maxHeight: 400,
  },
  chapterListContent: {
    paddingBottom: 10,
  },
  chapterMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#333',
    borderRadius: 8,
    marginBottom: 8,
  },
  chapterMenuItemSelected: {
    backgroundColor: '#444',
  },
  chapterMenuItemText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  chapterMenuCheck: {
    color: '#00ff88',
    fontSize: 20,
    fontWeight: 'bold',
  },
  viewModeButton: {
    minWidth: 35,
    maxWidth: 40,
  },
  viewModeButtonActive: {
    backgroundColor: '#555',
  },
  buttonDisabled: {
    backgroundColor: '#222',
    opacity: 0.5,
  },
  buttonTextDisabled: {
    color: '#666',
  },
  textViewContainer: {
    flex: 1,
    width: '100%',
    position: 'relative',
    marginTop: 165, // Space for chapter name (40) + progress bar (~100) + 25px margin
    paddingBottom: 20, // Extra padding at bottom for scrolling
  },
  textView: {
    flex: 1,
    width: '100%',
  },
  textViewContent: {
    padding: 20,
    paddingTop: 20,
    flexGrow: 1,
    justifyContent: 'center',
  },
  centeredTextView: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    maxWidth: 800,
    alignSelf: 'center',
    width: '100%',
  },
  paragraphText: {
    lineHeight: 32,
    textAlign: 'left',
  },
  pageText: {
    lineHeight: 32,
    textAlign: 'left',
  },
  customColorContainer: {
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  colorPickerButton: {
    backgroundColor: '#444',
    padding: 10,
    borderRadius: 8,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorPickerButtonText: {
    fontSize: 20,
  },
  colorPickerModalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  colorPreview: {
    width: '100%',
    height: 80,
    borderRadius: 8,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#555',
  },
  colorPreviewText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  colorPickerSliders: {
    width: '100%',
    marginBottom: 20,
  },
  colorSliderRow: {
    marginBottom: 15,
  },
  colorSliderLabel: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 5,
    fontWeight: '600',
  },
  colorSlider: {
    width: '100%',
    height: 40,
  },
  quickColorsContainer: {
    width: '100%',
    marginBottom: 20,
  },
  quickColorsLabel: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 10,
    fontWeight: '600',
  },
  quickColorsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickColorOption: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#555',
  },
  colorPickerActions: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
  },
  settingSubLabel: {
    fontSize: 14,
    color: '#ccc',
    marginRight: 10,
  },
  colorInput: {
    flex: 1,
    backgroundColor: '#333',
    color: '#fff',
    padding: 10,
    borderRadius: 6,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#555',
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wordSelectionContainer: {
    marginVertical: 20,
  },
  wordSelectionText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
  },
  wordSelectionButton: {
    backgroundColor: '#333',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
  },
  wordSelectionButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  modalSubtitle: {
    color: '#999',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  rsvpPrompt: {
    position: 'absolute',
    bottom: 100,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    padding: 10,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
    zIndex: 1000,
    minWidth: 140,
    maxWidth: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  rsvpPromptButton: {
    padding: 8,
    borderRadius: 6,
    alignItems: 'center',
    width: '100%',
  },
  rsvpPromptButtonText: {
    color: '#000',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modalButtonTextWhite: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  fontPickerButton: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#555',
  },
  fontPickerButtonText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  fontPickerButtonArrow: {
    color: '#999',
    fontSize: 12,
    marginLeft: 10,
  },
  fontList: {
    maxHeight: 400,
  },
  fontListContent: {
    paddingBottom: 10,
  },
  fontMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#333',
    borderRadius: 8,
    marginBottom: 8,
  },
  fontMenuItemSelected: {
    backgroundColor: '#444',
  },
  fontMenuItemText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  fontMenuCheck: {
    color: '#00ff88',
    fontSize: 20,
    fontWeight: 'bold',
  },
});
